version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Instalar openssh
          command: |
            sudo apt update && sudo apt install -y openssh-client

      - add_ssh_keys:
          fingerprints:
            - "placeholder"  # no hace falta si usamos clave vía variable ENV

      - run:
          name: Crear archivo de clave privada
          command: |
            echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key

      - run:
          name: Copiar código al servidor
          command: |
            scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r . usuario@ip-remota:/home/usuario/app-flask

      - run:
          name: Ejecutar app en el servidor
          command: |
            ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no usuario@ip-remota "
              cd /home/usuario/app-flask &&
              nohup python3 backend/app.py > app.log 2>&1 &
            "

workflows:
  version: 2
  deploy-on-push:
    jobs:
      - deploy

