version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Crear entorno virtual
          command: python -m venv venv
      - run:
          name: Instalar dependencias
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Ejecutar tests
          command: |
            . venv/bin/activate
            pytest backend/tests

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Simular despliegue
          command: echo "Despliegue exitoso"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
